<?php 

/*
    Template Name: Legales-cgs
*/

get_header(); ?>
<div>
    <main>
        <section class="landing-legal-section">
            <div class="landing-legal-container">
                <h1>Conditions générales de service</h1>
            </div>
        </section>
        <section class="paragraphe-legal-section">
            <div class="paragraphe-legal-container">
                <h2>Cours particuliers</h2>
                <p>
                    Le recours aux services de prestations de la société Anacours SARL, dont le nom commercial est ANACOURS (ou toute autre personne morale qui s’y substituerait) et dont le siège social est au 13 rue Madame de Sanzillon 92110 Clichy, RCS Paris 441 460 375, déclarée sous le numéro SAP441460375 entraîne l’acceptation des conditions suivantes :
                    <br><br>
                    <b>Frais d’inscription :</b> Les frais d’inscription, dont le montant TTC est précisé par écrit, sont dus avant le début de l’intervention pour pouvoir bénéficier des prestations d’ANACOURS Les frais d’inscription sont valables par foyer fiscal et par année scolaire. Ils sont définitivement acquis à ANACOURS sauf si à l’issue du premier cours le particulier employeur décide d’arrêter les cours. Dans ce cas, les frais d’inscription lui seraient remboursés déduction faite du montant du premier cours.
                    <br><br>
                    <b>Mandat :</b> ANACOURS est un organisme de services à la personne déclaré en mode mandataire dans le cadre des dispositions des articles L7232-6 et L7233-1 du code du travail. Le consommateur signe un mandat aux termes duquel il confie à ANACOURS la présélection et la présentation d’intervenants ainsi que la réalisation de formalités et déclarations administratives lui incombant en sa qualité d’employeur d’intervenant à domicile : immatriculation, réalisation des fiches de paye, documents de fin de contrat, paiement des salaires et charges sociales. Le détail des tâches confiées est explicité dans le mandat. La signature du mandat est obligatoire pour bénéficier des services d’ANACOURS. Le particulier employeur autorise par ailleurs ANACOURS, qui l’accepte, à recevoir toute correspondance de l’Urssaf ou de tous les organismes administratifs, sociaux ou fiscaux, qui lui est destinée, et à utiliser tous moyens dématérialisés dans ses échanges avec ces organismes. Le particulier employeur mandate ANACOURS, qui l’accepte, pour télétransmettre à l’Urssaf pour son compte les informations sociales périodiques et les règlements associés. Le particulier employeur reconnaît expressément être l’employeur des enseignants présentés par ANACOURS. Le mandat dûment complété doit être retourné à ANACOURS dès la souscription du service. Il est conclu pour une durée indéterminée et s’applique pour chaque cours délivré par un enseignant à domicile présenté par ANACOURS.
                    <br><br>
                    <b>Utilisation des coupons-contrats :</b><br>
                    Le particulier employeur doit obligatoirement utiliser les coupons-contrats délivrés par ANACOURS permettant la rémunération de l’enseignant. Chaque coupon-contrat matérialise une heure de cours. Les coupons-contrats sont valides pendant l’année scolaire de leur émission ainsi que l’année scolaire suivante, moyennant, le cas échéant, paiement d’un complément pour ajustement aux salaires et frais professionnels de l’enseignant ou aux prestations d’ANACOURS. Les coupons-contrats peuvent faire l’objet d’une demande de remboursement pendant un an à compter de leur date d’émission, en adressant un courrier recommandé à ANACOURS. En cas de remboursement, une retenue pour frais de gestion de 5 Euros TTC par coupon-contrat est demandée, et dans le cas où la commande de coupons-contrats a bénéficié d’une réduction liée au volume de la commande, le montant remboursé est calculé en tenant compte des coupons-contrats réellement utilisés. Les sommes payées par Cesu ne peuvent pas faire l’objet de remboursement. En cas de rejet de paiement ou de perte des coupons contrats, des frais de traitement d’un montant de 15 Euros TTC seront appliqués. 
                    <br><br>
                    <b>Relations entre le particulier employeur et l’enseignant :</b> Le particulier employeur est seul et unique employeur des enseignants employés à son domicile pour assurer des cours de soutien scolaire. En tant qu’employeur, le particulier employeur reste libre d’accepter ou non les enseignants proposés par ANACOURS et de définir avec eux les moyens pédagogiques à mettre en œuvre, le rythme, les horaires et la durée de ses interventions, ainsi que définir le salaire horaire. Attention, dans le cadre d’un contrat de placement de travailleurs, dit mode mandataire, le consommateur est l’employeur de la personne qui effectue la prestation à son domicile. En cette qualité d’employeur, le consommateur est soumis à diverses obligations résultant notamment du code du travail, du code de la sécurité sociale et la convention collective nationale du Particulier Employeur n°3180 disponible sur demande. Les obligations liées à la signature et à la forme du contrat de travail ainsi qu’au suivi médical du salarié demeurent la responsabilité du particulier employeur et de son salarié. Des modèles de contrats de travail sont disponibles dans la convention collective nationale des salariés du particulier employeur ou sur le site cesu.urssaf.fr. L’enseignant peut demander au particulier employeur d’accéder à la formation professionnelle continue, notamment pour une formation à la sécurité. ANACOURS peut aider à l’élaboration du plan de formation des enseignants. Le particulier employeur et les enseignants doivent chacun être couverts par une assurance responsabilité civile. Le particulier employeur est invité à vérifier auprès de l’assureur de son habitation la nature et les limites des garanties prévues à son contrat d’assurance concernant les dégâts et dommages causés par ou à son salarié à domicile.
                    <br><br>
                    <b>Rémunération des enseignants salariés par le particulier employeur :</b> L’enseignant a préalablement accepté la rémunération horaire proposée par le particulier employeur. Les enseignants ont mandaté ANACOURS pour récupérer les salaires, les indemnités de transport et les indemnités pédagogiques qui leur sont dus par les particuliers employeurs. Le particulier employeur mandate quant à lui ANACOURS pour verser pour son compte aux enseignants les salaires, les indemnités de transport et les indemnités pédagogiques qui leur sont dus et aux organismes compétents les cotisations sociales correspondantes. Pour remplir ces deux mandats de paiement, le particulier employeur adresse à ANACOURS l’ensemble des salaires ainsi que les indemnités de transports et les indemnités pédagogiques à verser aux enseignants et les cotisations sociales afférentes. A la fin de chaque séance, le particulier employeur remet à l’enseignant le nombre de coupons-contrats correspondant au nombre d’heures de cours dispensées. Au nom et pour le compte du particulier employeur, ANACOURS reverse à l’enseignant son salaire, les indemnités de transport et les indemnités pédagogiques sur remise à ANACOURS des coupons-contrats et reverse les cotisations sociales correspondantes aux organismes compétents. En aucun cas, ANACOURS ne pourra reverser aux enseignants et aux organismes sociaux des montants supérieurs aux sommes reçues. En aucun cas, ANACOURS ne pourra être tenu responsable des obligations du particulier employeur notamment en ce qui concerne le versement des salaires, des indemnités de transport, des indemnités pédagogiques et des cotisations sociales si ceux-ci n’ont pas été adressés à ANACOURS ou des obligations légales à l’égard des enseignants. L’enseignant accepte expressément que le Mandataire lui remette, au nom et pour le compte du particulier-employeur qui l’emploie, les bulletins de paie et les notes de remboursements d’indemnités de transport et autres frais professionnels qui lui sont dus. Ces documents, établis sur les instructions du particulier employeur seront mis à disposition en projet sur l’extranet du Mandataire le 1er du mois suivant son activité et pendant un délai de 3 jours ouvrés. L’absence d’observation de la part de l’enseignant au cours de ce délai vaut validation desdits documents et des bases financières indiquées. Le Mandataire, en cas de validation du particulier employeur, pourra alors réaliser l’ensemble des démarches et déclarations auprès de l’URSSAF selon les informations et bases financières indiquées.
                    <br><br>
                    <b>Avantage fiscal :</b> Le recours aux services à la personne à domicile peut ouvrir droit à un avantage fiscal égal à 50% des sommes effectivement engagées dans les conditions de l’article 199 sexdecies du Code général des Impôts auquel le consommateur est invité à se reporter.
                    <br><br>
                    <b>Résiliation du mandat :</b> Le mandat peut être résilié à tout moment sans préavis à l’initiative de l’une ou de l’autre des parties et sans contrepartie financière sous réserve qu’ANACOURS ait réalisé l’ensemble de ses obligations dans le cadre du mandat. Si le particulier employeur décide d’employer un enseignant présenté par ANACOURS sans recourir aux services d’ANACOURS, il lui sera facturé la somme de 750 € TTC en règlement des frais de présentation et de placement de cet enseignant. Il est rappelé que le travail dissimulé est passible de sanctions pénales.
                    <br><br>
                    <b>Droit de rétractation :</b> Le particulier employeur dispose d’un délai de 14 jours à compter de sa commande pour exercer son droit de rétraction en adressant un courrier postal à son agence Anacours. Un formulaire de rétractation est disponible à l’adresse suivante <a href="https://www.anacours.com/images/formulaire_retractation.pdf" target="_blank">https://www.anacours.com/images/formulaire_retractation.pdf</a>. Si le particulier employeur a demandé expressément à Anacours à commencer la prestation avant la fin du délai de rétractation, il reste redevable du coût des prestations réalisées jusqu’à la réception de sa rétractation par Anacours.
                    <br><br>
                    <b>Droit applicable :</b> Pour tout litige non résolu après demande écrite préalable du particulier employeur auprès d’ANACOURS, celui-ci peut recourir gratuitement au médiateur de la consommation de l’AME conso (11 place Dauphine 75001 Paris, <a href="https://www.anacours.com/images/formulaire_retractation.pdf" target="_blank">www.mediationconso-ame.com</a>) en vue de la résolution amiable du litige. Tout différend qui pourrait naître entre les parties quant à la validité, l’interprétation ou l’exécution des présentes sera soumis, à défaut d’accord amiable entre les parties, aux juridictions compétentes.
                    <br><br>
                    <b>Protection des données :</b> ANACOURS s’engage à préserver la confidentialité des informations communiquées par le particulier employeur. Conformément à la loi Informatique et liberté n° 78-17 datant du 6/01/1978, le particulier dispose d’un droit d’accès, de rectification et de suppression des données le concernant qu’il peut exercer en s’adressant à ANACOURS, 13 rue Madame de Sanzillon 92110 Clichy.
                </p>
                <h2>Stages et cours en agence</h2>
                <p>
                    <b>Tarifs et inscription :</b> Les tarifs indiqués sont des prix TTC tenant compte de la TVA applicable au jour de la commande. Tout changement de taux pourra être répercuté sur le prix des services. Toute inscription à nos stages suppose que le client accepte le contenu du stage et s’assure de disposer des pré-requis. Dans ce cas, les inscriptions sont prises par ordre d’arrivée et dans la limite des places disponibles.
                    <br><br>
                    <b>Droit de rétractation :</b> Le souscripteur dispose d’un délai de 14 jours à compter de sa commande pour exercer son droit de rétraction en adressant un courrier postal à son agence Anacours. Si le souscripteur a demandé expressément à Anacours à commencer la prestation avant la fin du délai de rétractation, il reste redevable du coût des prestations réalisées jusqu’à la réception de sa rétractation par Anacours.
                    <br><br>
                    <b>Modalités de paiement :</b> Le paiement est exigible à la commande. Le paiement des prestations en agence s’effectue par carte bancaire, chèque ou espèces et doit être effectué en totalité 48 heures ouvrées avant le début des prestations.
                    <br><br>
                    Annulation : Pour les stages de vacances en groupes, toute annulation doit faire l’objet d’un écrit au moins 72 heures ouvrées avant le début du stage. À tout moment, Anacours rembourse, au prorata, toute absence pour des raisons de santé sur présentation d’un certificat médical, à réception de celui-ci. Dans le cas où l’annulation est du fait d’Anacours, le stage sera remboursé dans son intégralité. Anacours peut être amené à modifier le lieu où l’horaire d’un stage et s’engage à en informer le client au moins 48 heures avant le début du stage.
                    <br>
                    Pour les autres cours en agences, les cours commandés ne sont pas remboursables. Dans le cas où l’annulation est du fait d’Anacours, les cours seront remboursés dans leur intégralité. Anacours peut être amené à modifier le lieu où l’horaire d’un cours et s’engage à en informer le client au moins 48 heures avant le début du cours.
                </p>
            </div>
        </section>
    </main>
</div>
<?php get_footer();